/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lixiangers_androidresearch_feature_NDKUtil */

#ifndef _Included_com_lixiangers_androidresearch_feature_NDKUtil
#define _Included_com_lixiangers_androidresearch_feature_NDKUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lixiangers_androidresearch_feature_NDKUtil
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lixiangers_androidresearch_feature_NDKUtil_getStringFormC
  (JNIEnv *, jclass);

/*
 * Class:     com_lixiangers_androidresearch_feature_NDKUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lixiangers_androidresearch_feature_NDKUtil_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
